### ISSUE TITLE
Inquiry About Missing Database Backup File for Sports Store Management System

### ISSUE THREAD

**Issue by MagicYellow623** [TheAnirudhRoy/SportsStoreManagementSystem#1]
Dear Anirudh Roy,

I hope this message finds you well.

I am currently trying to replicate the Sports Store Management System project from your GitHub repository. I have followed the provided instructions in the README file but encountered an issue when attempting to download the database backup file. The link to the .bak file appears to be missing or broken.

Could you kindly provide the correct link or upload the database backup file to the repository? Your assistance would be greatly appreciated as it is crucial for setting up and running the project successfully.

Thank you very much for your time and help.

**Comment by TheAnirudhRoy** [comment]
Hi Magic Yellow, the DB has been uploaded now, you can check. Thanks
